services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile   #  ganti kalau struktur docker beda
    container_name: ayumi-management_app         #  GANTI: nama project
    volumes:
      - .:/var/www                        #  kalau bukan PHP, biasanya /app atau /usr/src/app
    depends_on:
      - db
    expose:
      - "9000"                            #  ganti kalau framework bukan php-fpm
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: ayumi-management_nginx       #  GANTI: nama project
    ports:
      - "8000:80"                         #  GANTI: port host kalau tabrakan
    volumes:
      - .:/var/www                        #  sesuaikan dengan root app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: ayumi-management_db          #  GANTI: nama project
    environment:
      MYSQL_DATABASE: ayumi_management_system     #  GANTI: nama DB
      MYSQL_ROOT_PASSWORD: root           #  ganti kalau mau aman
      MYSQL_ROOT_HOST: "%" 
    ports:
      - "3306:3306"                       #  ganti kalau MySQL lu bentrok
    volumes:
      - ayumi-management_db_data:/var/lib/mysql 
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ayumi-management_myadmin     #  GANTI: nama project
    ports:
      - "8080:80"                         #  ganti kalau bentrok
    environment:
      PMA_HOST: db                        # ini harus sama dengan nama service db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
volumes:
  ayumi-management_db_data: